disabled = false
languageCode = "en"
languageName = "English"
weight = 2
title = "The Little Jo's Blog"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  orderSectionsBy = "weight"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Joseph Ligier"
  #email = ""
  image = "img/littlejo.jpg"
  imageQuality = 96
  headline = "A little bit of this and that"
  bio = "CNCF ambassador | Kubestronaut 🐝"
  links = [
    { bluesky = "https://bsky.app/profile/littlejo.bsky.social" },
    { linkedin = "https://www.linkedin.com/in/joseph-ligier-4b86632" },
    { dev = "https://dev.to/littlejo" },
    { medium = "https://medium.com/@littel.jo" },
    { github = "https://github.com/littlejo" },
    { ko-fi = "https://ko-fi.com/littlejo" },
    #{ email = "mailto:hello@your_domain.com" },
    #{ link = "https://link-to-some-website.com/" },
    #{ gitlab = "https://gitlab.com/username" },
    #{ twitch = "https://twitch.tv/username" },
    #{ tiktok = "https://tiktok.com/@username" },
    #{ patreon = "https://www.patreon.com/username" },
  ]
